### ISSUE TITLE
Requesting progress check for importFilterHypermutators

### ISSUE THREAD

**Issue by wonjunetai** [hyginn/rete#44]
Namely, question on line 77.
Also want to check approach for processing each file.

**Comment by hyginn** [comment]
comments added

**Comment by hyginn** [comment]
*"approach for processing each file."* - you use the hashed environment with all of its getters (ls()) and setters (assign())  ... and that's very different from what I would have done since this are all non-vectorized functions. I would have built a data frame of samples from colnames(rCNA), and used fastmatch::fmatch() to access the columns you need; then taken the sample-names from the SNV as unique(rSNV$<whatever the column is called>), done at set-diff with the rownames of the table, and added the rows for the new samples en-bloc. Then again fastmatch::fmatch() to process all of the SNVs. Your approach is not wrong, I just have the *suspicion* that it may be quite slow, what with the element by element access of the environment, and replacing list items.
