### ISSUE TITLE
Requested review of psuedocode for importConservation

### ISSUE THREAD

**Issue by Adriel-M** [hyginn/rete#91]
(https://github.com/hyginn/rete/pull/90)

**Comment by hyginn** [comment]
I think this is fine - I had already seen it; you'll need to make a design decision whether to store chromosome coordinates in a column of your data matrix, or use a (very, very large) vector of chromosome-size where you just use the index as coordinate position. I'm a bit wary of the resource requirements this entails. It may be oK since this is not a general-use function ...

Please continue.
